// <auto-generated />
namespace Aplicacao.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datahora : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datahora));
        
        string IMigrationMetadata.Id
        {
            get { return "201706082333154_datahora"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
